# Generated by Django 4.1.5 on 2023-01-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="title",
            field=models.CharField(max_length=32, null=True, verbose_name="标题"),
        ),
    ]
