# Generated by Django 4.1.5 on 2023-01-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0002_alter_department_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="title",
            field=models.CharField(max_length=32, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="depart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_1.department",
                verbose_name="部门",
            ),
        ),
    ]
